# golangci-lint configuration
# Run: golangci-lint run ./...

version: "2"

formatters:
  enable:
    - gofmt
    - goimports

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - bodyclose
    - gocritic

  disable:
    - exhaustive
    - funlen
    - lll
    - wsl

  exclusions:
    rules:
      # Ignore errcheck in test and benchmark files
      - path: _test\.go
        linters:
          - errcheck
          - unused
          - gocritic
      # Ignore SA5011 nil pointer checks in tests (intentional for error checking)
      - path: _test\.go
        linters:
          - staticcheck
        text: "SA5011"

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
